# Generated by Django 6.0.6 on 2026-07-07 11:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('discount', models.CharField(max_length=100)),
                ('type', models.CharField(default='Percentage', max_length=50)),
                ('usage', models.IntegerField(default=0)),
                ('status', models.CharField(default='Active', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=100)),
                ('period', models.CharField(default='Monthly', max_length=50)),
                ('users_count', models.IntegerField(default=0)),
                ('status', models.CharField(default='Active', max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='application',
            name='applied_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='job',
            name='posted_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
