# Generated by Django 6.0.6 on 2026-07-07 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_coupon_subscriptionplan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='temp_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
