# Generated by Django 6.0.6 on 2026-07-08 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_candidate_country_candidate_linkedin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIRecommendation',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=100)),
                ('recommendation_text', models.TextField()),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_recommendations', to='api.candidate')),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentResult',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('test_name', models.CharField(max_length=255)),
                ('score', models.IntegerField()),
                ('total_questions', models.IntegerField()),
                ('correct_answers', models.IntegerField()),
                ('taken_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_results', to='api.candidate')),
            ],
        ),
        migrations.CreateModel(
            name='CareerRoadmap',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('target_role', models.CharField(max_length=255)),
                ('roadmap_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_roadmaps', to='api.candidate')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyInsight',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255)),
                ('insight_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_insights', to='api.candidate')),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(default='New Conversation', max_length=255)),
                ('is_favorite', models.BooleanField(default=False)),
                ('is_pinned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='api.candidate')),
            ],
        ),
        migrations.CreateModel(
            name='ConversationMessage',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('sender', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.conversation')),
            ],
        ),
        migrations.CreateModel(
            name='CoverLetter',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('letter_text', models.TextField()),
                ('tone', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cover_letters', to='api.candidate')),
            ],
        ),
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('round_type', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=255)),
                ('questions', models.JSONField(default=list)),
                ('answers', models.JSONField(default=dict)),
                ('evaluation', models.JSONField(default=dict)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_sessions', to='api.candidate')),
            ],
        ),
        migrations.CreateModel(
            name='JobMatchAnalysis',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('match_score', models.IntegerField(default=0)),
                ('analysis_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_matches', to='api.candidate')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.job')),
            ],
        ),
        migrations.CreateModel(
            name='LearningRecommendation',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('skill_name', models.CharField(max_length=255)),
                ('courses', models.JSONField(default=list)),
                ('books', models.JSONField(default=list)),
                ('projects', models.JSONField(default=list)),
                ('youtube', models.JSONField(default=list)),
                ('blogs', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_recommendations', to='api.candidate')),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('file_url', models.CharField(blank=True, default='', max_length=500)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('content_text', models.TextField(blank=True, default='')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='api.candidate')),
            ],
        ),
        migrations.CreateModel(
            name='ResumeAnalysis',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('ats_score', models.IntegerField(default=0)),
                ('formatting_score', models.IntegerField(default=0)),
                ('grammar_score', models.IntegerField(default=0)),
                ('keyword_score', models.IntegerField(default=0)),
                ('analysis_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_analyses', to='api.candidate')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='api.resume')),
            ],
        ),
        migrations.CreateModel(
            name='ResumeOptimization',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('before_content', models.JSONField(default=dict)),
                ('after_content', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_optimizations', to='api.candidate')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optimizations', to='api.resume')),
            ],
        ),
        migrations.CreateModel(
            name='ResumeVersion',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('version_number', models.IntegerField(default=1)),
                ('name', models.CharField(max_length=255)),
                ('content_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='api.resume')),
            ],
        ),
        migrations.CreateModel(
            name='SalaryPrediction',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('experience', models.FloatField()),
                ('skills', models.JSONField(default=list)),
                ('location', models.CharField(max_length=255)),
                ('min_salary', models.FloatField()),
                ('avg_salary', models.FloatField()),
                ('max_salary', models.FloatField()),
                ('market_demand', models.CharField(max_length=100)),
                ('growth_rate', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_predictions', to='api.candidate')),
            ],
        ),
        migrations.CreateModel(
            name='SkillGapAnalysis',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=255)),
                ('job_description', models.TextField()),
                ('analysis_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_gaps', to='api.candidate')),
            ],
        ),
    ]
